server.port: 9090
demo.security.jwt:
  tokenExpirationTime: 10080 # Number of minutes
  tokenIssuer: http://localhost
  tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus

spring.datasource:
  url: "jdbc:mysql://localhost:3306/contactsbook"
  username: "root"
  password: "root"
spring:
  jpa:
    hibernate:
      ddl-auto: create
